name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Make
        run: make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
